fix(ble): fix race condition for MAC addr device ID
memfault/sdk-nrf pull request #24
Opened 2024-06-13 21:11 UTC by gminn

2024-06-13 21:11 UTC, gminn commented
* **#24** <a href="https://app.graphite.dev/github/pr/memfault/sdk-nrf/24?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gminn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-20 06:12 UTC, ejohnso49 reviewed
Thought about this more, and I think I've sadly come to the conclusion that we just shouldn't try to use this for the BLE MAC case. I think that IMEI and network MAC are fine to keep in. Maybe we add a little blurb to the Kconfig to indicate this is for a network MAC (ie nrf7002).

Also I realized that the device serial isn't needed for reboot events 😑 should have remembered that. There's a Memfault config to include device serial with events but it's disabled by default because nearly all devices use the device serial in the chunks POST url.

2024-07-22 23:26 UTC, gminn commented
> Thought about this more, and I think I've sadly come to the conclusion that we just shouldn't try to use this for the BLE MAC case.

To clarify -- you're thinking we remove the example of using the BLE MAC addr for the device id?

2024-09-05 14:51 UTC, gminn commented
> To clarify -- you're thinking we remove the example of using the BLE MAC addr for the device id?

@ejohnso49 This is back on my radar and I applied your suggestions -- let me know what you think!

2024-09-05 15:12 UTC, ejohnso49 requested changes

2024-09-05 15:12 UTC, ejohnso49 commented on modules/memfault-firmware-sdk/Kconfig
> +	depends on !BT
I think this might need to be removed because a 7002 application with an nRF53 would still use the BLE stack. I think your other changes cover things as best as we can

2024-09-05 17:41 UTC, gminn commented on modules/memfault-firmware-sdk/Kconfig
> +	depends on !BT
Ah yes good point. I double checked after removing this that we get a proper MAC address device id 👍

```
uart:~$ mflt get_device_info
[00:00:12.471,466] <inf> mflt: S/N: F4CE3600260E
[00:00:12.471,496] <inf> mflt: SW type: nrf7002_nrf53-fw
[00:00:12.471,527] <inf> mflt: SW version: 0.0.1+cf5686
[00:00:12.471,557] <inf> mflt: HW version: nrf7002dk
```

added to the `samples/wifi/shell` app's `prj.conf` to get that build:
```
CONFIG_MEMFAULT=y
CONFIG_MEMFAULT_SHELL=y
CONFIG_MEMFAULT_LOGGING_ENABLE=y
CONFIG_MEMFAULT_LOG_LEVEL_INF=y

CONFIG_BT=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Nordic_Memfault"
CONFIG_BT_PRIVACY=y
```

and then built with
```
west build --pristine always --board nrf7002dk/nrf5340/cpuapp nrf/samples/wifi/shell -- -DCONFIG_MEMFAULT_NCS_PROJECT_KEY=\"dummy\"
```

2024-09-06 16:12 UTC, ejohnso49 approved these changes
Thanks for tackling this, at least we won't have blank device serial's by default

2024-10-18 16:38 UTC, gminn reviewed
Merged upstream in https://github.com/nrfconnect/sdk-nrf/commit/f3f5ff68b0ca5d680dc4ad31b6304f48eb61449e !

2024-10-18 16:38 UTC, closed without merging